### ISSUE TITLE
Seite mit eigenen Pflanzen erstellen 

### ISSUE THREAD

**Issue by sharii9** [AndreaChazarreta/PflanzenKleinanzeige#17]
- [x] Seller kann nur seine eigenen Pflanzen bearbeiten/editieren -> evtl. Lösung ist, dass nur die eigenen Pflanzen angezeigt werden und nur bei denen kann man diese bearbeiten (Andrea hat dies bereits in Löschen editiert 
- [x] Löschen, deaktivieren, Foto ändern und bearbeiten ist auf dieser Seite möglich
- [x] Deaktivierte Pflanzen dürfen nciht angezeigt werden auf der eigenen Pflanzenübericht und der allgemeinen
- [x] Keine Error-Message beim deaktvieren 
- [x] Informations Button beim Lösch Button?
- [x] Links verbessern
- [x] Seiten switch zwischen meine gekauften Pflanzen, meine verkauften Pflanzen und meine Merkliste  (Bootstrap nav & tabs )
- [x] Suchleiste editieren

**Comment by AndreaChazarreta** [comment]
@sharii9: ich glaube die Methoden braucht man nicht, da wir das direkt als Entity Attribut zur Verfügung haben :) 
(ich wollte eine extra Branche machen, um die Sachen zu löschen, damit du das dir erstmal anschauen kannst, und mich eventuell korrigieren, aber ich habs vergessen. Sorry!!!). 

Sollte man die Methoden doch brauchen, füge die gerne wieder ein :)
